backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

backend/blog/urls.py
from django.urls import path
from . import views
from .views import CategoryView

app_name = 'blog'

urlpatterns = [
    # post views
    #path('', views.post_list, name='post_list'),
    path('', views.post_list, name='home'),
    path('blog/', views.PostListViewBlog.as_view(), name='blog'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('category/<slug:slug>/', views.post_list, name='category-detail'),
]

backend/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.db.models import Count
# Create your models here.

class PublishedManager(models.Manager):
     # get_queryset() là phương thức mặc định để lấy queryset.
     def get_queryset(self):
          return super().get_queryset()\
                      .filter(status=Post.Status.PUBLISHED)

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True, help_text="Slug được tạo tự động từ tên, dùng cho URL.")

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category-detail', kwargs={'slug': self.slug})

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    objects = models.Manager()          # The default manager.
    published = PublishedManager()      # Our custom manager.
    tags = TaggableManager()
    categories = models.ManyToManyField(Category, related_name='posts', blank=False)

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def get_absolute_url(self):
        # viewname: '{app_name}:{views_name}'
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

backend/blog/forms.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

backend/blog/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm
from django.core.mail import send_mail
from taggit.models import Tag

# Create your views here.
def post_list(request,  tag_slug=None):
    post_list = Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    """How to use panigator
        from django.core.paginator import Paginator

        objects = ["item1", "item2", "item3", "item4", "item5", "item6", "item7", "item8", "item9", "item10"]
        p = Paginator(objects, 4)       # Each page will have 4 items
        p.count -> number of posts: 10
        p.pages -> number of pages: 3
        page1 = p.page(1) 
        print(page1.object_list) -> access page1 result = : ['item1', 'item2', 'item3', 'item4']
    """
    # Pagination with 3 posts per page
    paginator = Paginator(post_list, 3)
    # Get 'page' parameter from request.GET and assigns a default value of 1 if no 'page' parameter is passed.
    # If a user visits the URL: http://example.com/?page=3, the page_number will be 3.
    # If the user visits the URL: http://example.com/, the page_number will be 1 (default value).
    page_number = request.GET.get('page', 1)
    # Visit the corresponding page to get the list of articles
    try:
        posts = paginator.get_page(page_number)
    except EmptyPage:
        # If page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        # If page_number is not an integer deliver the first page
        posts = paginator.page(1)

    # Call file templates/post/list.html
    return render(request, '_blog/post/home.html', {'posts': posts, 'tag': tag})

def post_detail(request, slug):
    post = get_object_or_404(Post,
                             slug=slug,
                             status=Post.Status.PUBLISHED)

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request,
                  '_blog/post/post_detail.html',
                  {'post': post, 'similar_posts': similar_posts})

class PostListView(ListView):
    """
    Alternative post list view
    """
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = '_blog/post/home.html'

class PostListViewBlog(ListView):
    """
    Alternative post list view
    """
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = '_blog/post/blog.html'

class CategoryView(ListView):
    model = Post
    template_name = 'category_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.get(slug=self.kwargs['slug'])
        return context

backend/templates/_blog/default.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/_base.css' %}" rel="stylesheet">
        <link href="{% static 'css/_default.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Fira+Code&display=swap" rel="stylesheet">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div class="container">
            <div class="header-container">
                {% include "_include/header.html"%}
            </div>
            <div class="w-100 d-flex justify-content-center">
                <div class="custom-border-top-line"></div>
            </div>
            <div class="content-container">
                <p>
                    This is my blog.
                    I've written {% total_posts %} posts so far.
                </p>
                <h3>Latest posts</h3>
                     {% show_latest_posts 3 %}
                <div>
                    <h2>Categories</h2>
                    {% show_categories %}
                </div>
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

backend/templates/_blog/post/blog.html
{% extends "../default.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>Post Blog Linux</h1>
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "../../pagination.html" with page=page_obj %}
{% endblock %}

backend/templates/_blog/post/category_list.html
<ul>
    {% for category in categories %}
        <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
    {% endfor %}
</ul>

backend/templates/_blog/post/home.html
{% extends "../default.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>Post Blog</h1>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">
     Tags:
     {% for tag in post.tags.all %}
       <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
          {{ tag.name }}
       </a>
     {% if not forloop.last %}, {% endif %}
     {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }
  {% endfor %}
  {% include "../../pagination.html" with page=posts %}
{% endblock %}

backend/templates/_blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
  {% endfor %}
</ul>

backend/templates/_blog/post/post_detail.html
{% extends "../default.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown }}

  <h2>Similar posts</h2>
    {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
      There are no similar posts yet.
    {% endfor %}

  <div class="giscus">
    <script src="https://giscus.app/client.js"
          data-repo="ptmkhanh29/blog-embedded-django"
          data-repo-id="R_kgDOLvz8Nw"
          data-category="Announcements"
          data-category-id="DIC_kwDOLvz8N84CexL8"
          data-mapping="pathname"
          data-strict="0"
          data-reactions-enabled="1"
          data-emit-metadata="1"
          data-input-position="bottom"
          data-theme="preferred_color_scheme"
          data-lang="vi"
          crossorigin="anonymous"
          async>
    </script>
  </div>
{% endblock %}

backend/templates/_include/header.html
{% load static %}
<header class="header">
  <h3 class="header-title">
      <a href="{{ domain.url }}" class="typing">~/home/khanhphan</a>
      <div class="menu">
          <div class="header-subtitle">Software Engineer</div>
            <nav class="social-icons">
                {% for key, value in site.items %}
                    {% if value.url %}
                        <a href="{{ value.url }}/" target="_blank">
                            <img src="{% static value.icon %}" alt="{{ key }} icon" class="icon-border">
                        </a>
                    {% endif %}
                {% endfor %}
            </nav>
      </div>
      <div class="menu-content">
            {% for item in menu %}
                <a href="{{ domain.url }}{% if item.url %}{{ item.url }}/{% endif %}"
                   class="{% if request.path == '/' and not item.url or request.path == '/'|add:item.url|add:'/' %}active{% endif %}">
                    {{ item.name }}
                </a>
            {% endfor %}
      </div>
      <div class="mode" id="mode-switcher" onclick="toggleNightMode();">
        <span></span>
      </div>
  </h3>
</header>
<script>
  function toggleNightMode() {
      if (document.documentElement.getAttribute('data-theme') === 'light') {
          document.documentElement.setAttribute('data-theme', 'dark');
          document.getElementById('mode-switcher').classList.add('active');
          localStorage.setItem("theme", "dark");
      } else {
          document.documentElement.setAttribute('data-theme', 'light');
          document.getElementById('mode-switcher').classList.remove('active');
          localStorage.setItem("theme", "light");
      }
  }

  document.addEventListener('DOMContentLoaded', (event) => {
      const currentTheme = localStorage.getItem('theme') ? localStorage.getItem('theme') : 'light';
      document.documentElement.setAttribute('data-theme', currentTheme);
      if (currentTheme === 'dark') {
          document.getElementById('mode-switcher').classList.add('active');
      }
  });
</script>

backend/templates/_include/sidebar.html
{% load static %}
<!-- Sidebar content -->
<img src="{% static 'images/profile.jpg' %}" alt="Profile Image"> <!-- Provide a valid image path or URL -->
  <div class="site-title" role="heading" aria-level="1">
    <a href="{{ '/' }}">Khanh Phan</a>
  </div>
  <div class="site-subtitle fst-italic mb-0">Software Engineer|DevOps Engineer|Embedded Software Engineer</div>
<div class="w-100 d-flex justify-content-center">
        <div class="custom-border-top-line"></div>
    </div>
  <p>Hello! I'm [Your Name].</p> <!-- Replace with actual content or use template variables -->
  <p>Currently working as a [Your Position].</p> <!-- Replace or use variables -->
  <p>Based in Vietnam.</p>

<div class="mode" id="mode-switcher" onclick="toggleNightMode();">
  <span></span>
</div>
<script>
  function toggleNightMode() {
      if (document.documentElement.getAttribute('data-theme') === 'light') {
          document.documentElement.setAttribute('data-theme', 'dark');
          document.getElementById('mode-switcher').classList.add('active');
          localStorage.setItem("theme", "dark");
      } else {
          document.documentElement.setAttribute('data-theme', 'light');
          document.getElementById('mode-switcher').classList.remove('active');
          localStorage.setItem("theme", "light");
      }
  }

  document.addEventListener('DOMContentLoaded', (event) => {
      const currentTheme = localStorage.getItem('theme') ? localStorage.getItem('theme') : 'light';
      document.documentElement.setAttribute('data-theme', currentTheme);
      if (currentTheme === 'dark') {
          document.getElementById('mode-switcher').classList.add('active');
      }
  });
</script>

backend/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>